os:
  - linux
  - osx
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '11'
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - npm install winston@2.3.1
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
env:
  - CC=gcc-8 CXX=g++-8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - build-essential
      - libcairo2-dev
      - libpango1.0-dev
      - libjpeg-dev
      - libgif-dev
      - librsvg2-dev
  homebrew:
    packages:
      - clang-3.9
      - cairo
      - librsvg
      - jpeg-turbo
install:
- |
    if [[ "${CC}" =~ clang- ]]; then
      echo "Installing ${CC}."
      CC_VERSION=$(echo "${CC}" | sed -e 's/^clang-//')
      brew install "llvm@${CC_VERSION}"
      brew install libomp
      CC_PREFIX=$(brew --prefix "llvm@${CC_VERSION}")
      export PATH="${CC_PREFIX}/bin:$PATH"
      export LDFLAGS="-L${CC_PREFIX}/lib -Wl,-rpath,${CC_PREFIX}/lib"
      export CPPFLAGS="-I${CC_PREFIX}/include"
    fi
